- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    hostname: Nginx_nodejs
    instance_type: "t2.micro"
    image: "ami-775e4f16"
    group: "my rules"
    region: "us-west-2"
  tasks:
    - name: make one instance
      ec2: image={{ image }}
           instance_type={{ instance_type }}
           instance_tags='{ "Name":"{{ hostname }}" , "Group":"nginx_backend" }'
           region={{ region }}
           group={{ group }}
           wait=true
      register: ec2_host

    - debug: var=ec2_host
    - debug: var=item
      with_items: ec2_host.instance_ids

    - add_host: hostname={{ item.public_ip }} groupname=ec2hosts
      with_items: ec2_host.instances

    - name: wait for instances to listen on port:22
      wait_for:
        state=started
        host={{ item.public_dns_name }}
        port=22
      with_items: ec2_host.instances

- hosts: ec2hosts
  gather_facts: True
  user: ec2-user
  sudo: True
  vars:
     connections : "4096"

  tasks:
    - user: name=boyko shell=/bin/bash groups=wheel  append=yes

