---

#- name: Copy the code from repository
#  git: repo={{ repository }} 
#       dest=/var/www/html/enzo/  
- name: Setup the Git repo
  git: repo={{ repository }}
       dest={{ project_path }}
       accept_hostkey=True
       key_file="/home/marcs/.ssh/id_rsa"
